name: 'release'
on:
  push:
    branches:
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: ./
        with:
          github-token: ${{ secrets.github_token }}
