name: 'release'
on:
  push:
    branches:
      - 'releases/*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - run: yarn --production
      - run: git add node_modules -f

      - uses: ./
        with:
          github-token: ${{ secrets.github_token }}
