name: 'Tag latest release of action tagger :zap:'

on:
  release:
    types:
      - published
      - edited

jobs:
  run-tag-latest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Actions-R-Us/actions-tagger@latest
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
